### ISSUE TITLE
stored testing productIds

### ISSUE THREAD

**Issue by lorenx** [robotmedia/AndroidBillingLibrary#1]
testing products id are stored in the local database as they are ("android.test.purchased", "android.test.refunded"...) so that every transaction is indipendent from previous ones.

my proposal is something like the following.

in BillingDB:

```
private String fixPurchaseProductId(String purchaseProductId) {
    if (purchaseProductId.startsWith("android.test.")) return "android.test";
    return purchaseProductId;
}
```

and then:

```
public void insert(Purchase purchase) {
    //...
    values.put(COLUMN_PRODUCT_ID, fixPurchaseProductId(purchase.productId));
    //...
}

//...

public Cursor queryPurchases(String productId, PurchaseState state) {
    return mDb.query(TABLE_PURCHASES, TABLE_PURCHASES_COLUMNS, COLUMN_PRODUCT_ID + " = ? AND " + COLUMN_STATE + " = ?", 
        new String[] {fixPurchaseProductId(productId), String.valueOf(state.ordinal())}, null, null, null);
}
```

let me know, thanks.

**Comment by robotmedia** [comment]
Thanks lorenx.

What would be the advantage of saving all test transactions with the same id?

**Comment by lorenx** [comment]
let's see an example.

i first purchase my product:

```
requestPurchase("android.test.purchased")
```

and it stores productId="android.test.purchased", state=0;

then i request a refund:

```
requestPurchase("android.test.refunded")
```

and it stores productId="android.test.refunded", state=2;

in the end, isPurchased() method is ambiguous because if i call:

```
isPurchased("android.test.purchased")
```

it returns always true.

well, i just think that it has to be the "state" that store the state for the same productId.
am i wrong?

**Comment by robotmedia** [comment]
Got it. 

While this behavior would certainly be useful for testing, there's no documentation that says that test transactions should be treated like this and they're not treated like this in the official Android In-app Billing example (Dungeons). Thus, we think it's best to leave the identifiers of test transactions unmodified.

That said, isPurchased return true if the id has a purchased transaction and does not consider refunds or cancellations. We need to clarify this on the documentation and maybe add another method that does consider refunds and cancellations. Currently, finer-grain control of this can be achieved with getPurchases, but it's not optimal.
