### ISSUE TITLE
onPurchaseStateChanged() not called

### ISSUE THREAD

**Issue by sandscorpio** [robotmedia/AndroidBillingLibrary#102]
~~I am testing on a 2.3.6 Nexus One.
I am seeing that onPurchaseStateChanged() is not getting called, but onRequestPurchaseResponse() does get called on a successful purchase (with response RESULT_OK).
On my 4.1.1 Galaxy Nexus, onPurchaseStateChanged() is called on purchase.~~

It is happening on both devices. But for one app _onPurchaseStateChanged()_ is getting called, while on another app only _onRequestPurchaseResponse()_ is getting called. So it is not a device issue, but an app issue. What could it be? 

Thanks for the great library.

**Comment by sandscorpio** [comment]
Resolved. 

I wasn't calling _BillingController.setConfiguration()_

**Comment by ifra19** [comment]
where are you calling BillingController.setConfiguration() ?

**Comment by sandscorpio** [comment]
onCreate() at the application level. See http://developer.android.com/reference/android/app/Application.html
