### ISSUE TITLE
Compile problem in new Android Eclipse platform release 4.2 / 21.0.0.vxxx

### ISSUE THREAD

**Issue by powder366** [robotmedia/AndroidBillingLibrary#103]
Get a new compile error in the new Android Eclipse platform release 4.2.
--> Development tools release 21.0.0.v201210310015-519525   

Description Resource    Path    Location    Type
The method asBinder() of type IMarketBillingService.Stub must override a superclass method  IMarketBillingService.java  /AndroidBillingLibrary/gen/com/android/vending/billing  line 32 Java Problem

Description Resource    Path    Location    Type
The method asBinder() of type IMarketBillingService.Stub.Proxy must override a superclass method    IMarketBillingService.java  /AndroidBillingLibrary/gen/com/android/vending/billing  line 76 Java Problem

Description Resource    Path    Location    Type
The method sendBillingRequest(Bundle) of type IMarketBillingService.Stub.Proxy must override a superclass method    IMarketBillingService.java  /AndroidBillingLibrary/gen/com/android/vending/billing  line 85 Java Problem

**Comment by jayschwa** [comment]
Project specific compiler settings have to be turned off. I have the fix in my fork:
https://github.com/jayschwa/AndroidBillingLibrary/commit/f8b14f8b6f7b70aee755874eafb4e60f62233337

**Comment by TomTasche** [comment]
Guys, this error still occurs everytime I import the library into Eclipse. Turning of project specific compiler settings fixes it, as mentioned by @jayschwa.

**Comment by sourab-sharma** [comment]
or just change the java compiler compliance level from 1.5 to 1.6
