### ISSUE TITLE
How to handle refunds?

### ISSUE THREAD

**Issue by sandscorpio** [robotmedia/AndroidBillingLibrary#104]
There is no mention in documentation or tutorial on how to properly handle refunds. It is not clear what the action flow is and it is hard to test as well. Can somebody please add a _How to handle refunds_ to the README file? Thanks.

**Comment by jayschwa** [comment]
Your BillingObserver's onPurchaseStateChanged() will be called when a refund or cancellation occurs. What you decide to do from there is up to you.

**Comment by sandscorpio** [comment]
How will it be called if app is not running (since merchant does refund remotely) and user may not have the app open? Thanks.

**Comment by hpique** [comment]
@sandscorpio Reading the in-app billing documentation is a must before using this library, as indicated in the README.

**Comment by sandscorpio** [comment]
Sorry, I'm not getting it. I have read the in in-app billing documentation, but I don't see how it could work in this case.

From the in-app billing documentation, I see that the refund would be broadcasted and that makes sense. The receiver handling the broadcast notifies all observers.

But I don't see how any observer could be loaded since observers are tied to activities and the user could have the app closed, which means no activities are loaded. Therefore the refund notification would not be seen by my observer.

Cancellations would always get caught, since that happens within the app UI when activity and observer is loaded.

The only solution I'm seeing (the goal here is to disable previously purchased content on a refund) is to go through all transactions returned by _BillingController.getTransactions(this)_ and see per product how many purchases and refunds are there. _Does BillingController.isPurchased()_ account for refunds?

Thanks, and sorry if these are dumb questions..

**Comment by hpique** [comment]
> But I don't see how any observer could be loaded since observers are tied to activities 

No. You can add observers to BillingController directly.

**Comment by sandscorpio** [comment]
thanks. added observer at application level.
