### ISSUE TITLE
Cancelled purchase, getTransactions is still returning a value in one mobile but not the other with the same google account

### ISSUE THREAD

**Issue by powder366** [robotmedia/AndroidBillingLibrary#108]
Hi,

I cancelled and in app purchase. On one mobile everything worked fine.
Turning on my second mobile with the same google account my app is still 
responding as if I still own the cancelled item? I.e.

```
    List<Transaction> transactions = BillingController.getTransactions(this);
    for(Transaction t : transactions) {
        if(t.purchaseState == PurchaseState.PURCHASED) {
```

getTranscations returns a value and (t.purchaseState == PurchaseState.PURCHASED) is true

It seems that the transaction is still there? How can this be? Is it local not deleted or... need a hint how I can debug this...
Everything is live deployed in Play. Uninstalling and reinstalling from Play did not help.

-> After removing my account on the phone and adding it again solved the problem. It seems either this library or in-app is not working 100%

Help appreciated, Thanks!

**Comment by hpique** [comment]
Eventually your other installation should have received an IN_APP_NOTIFY broadcast to indicate that the purchase was cancelled. If that takes long or doesn't happen for whatever reason, there's not much the library can do.
