### ISSUE TITLE
Handling Developer Payload and OrderId

### ISSUE THREAD

**Issue by ifra19** [robotmedia/AndroidBillingLibrary#114]
I'm developing an app for production. So, do I have to handle Developer Payload and orderId or does this library handles them itself?

If I have to handle this, please guide me where/how do I handle them?

**Comment by BraisGabin** [comment]
You can use [BillingController.requestPurchase(Context, String, boolean, String)](https://github.com/robotmedia/AndroidBillingLibrary/blob/master/AndroidBillingLibrary/src/net/robotmedia/billing/BillingController.java#L578).

**Comment by ifra19** [comment]
Will it be okay, for a production app,  if I pass null in the last parameter(developer payload) of requestPurchase?  My app have only non-consumable products.

**Comment by BraisGabin** [comment]
This is not a QA site. For this questions use StackOverflow. And I recommend you read the documentation of billing.

And no, there is not problem.
