### ISSUE TITLE
Purchase States

### ISSUE THREAD

**Issue by and7ey** [robotmedia/AndroidBillingLibrary#13]
While testing the app, I see that purchase of _android.test.purchased_ is reflected in the database. But purchase status there is 0. Hence `isPurchased` returns false. 

I've checked possible states

``` java
    public enum PurchaseState {
        // Responses to requestPurchase or restoreTransactions.
        PURCHASED,    // 0: The charge failed on the server.
        CANCELLED,   // 1: User was charged for the order.
        REFUNDED;    // 2: User received a refund for the order.
```

Is everything correct here?

**Comment by robotmedia** [comment]
While the values of the `PurchaseState` enum are correct, the comments are mixed up. We will fix this ASAP.

isPurchased responds to correctly to all the unit tests. Maybe it's something else?
