### ISSUE TITLE
getObfuscationSalt example is needed

### ISSUE THREAD

**Issue by and7ey** [robotmedia/AndroidBillingLibrary#14]
Could you please provide me with example how `public byte[] getObfuscationSalt() {` can look like?

**Comment by robotmedia** [comment]
```
@Override
public byte[] getObfuscationSalt() {
    return new byte[] {-25, 76, 83, 24, 77, 54, -8, 57, 30, -113, -97, -58, 46, 59, 18, 35, -15, -65, 103, 108};
}
```

**Comment by and7ey** [comment]
Am I right to say that:
1) any numbers can be used
2) any quantity of numbers is supported
?

**Comment by robotmedia** [comment]
1) No. It's a byte array.

2) The javadoc says only 20 are needed.
