### ISSUE TITLE
I used requestPurchase it did the purchase but no UI on screen

### ISSUE THREAD

**Issue by tomer-ben-david** [robotmedia/AndroidBillingLibrary#15]
Hi

I used requestPurcahse it did the purchase but there was no UI on screen telling user to confirm a purchase for this item description from android market.

can this feature be added please with the requestPurchase?

thanks

**Comment by robotmedia** [comment]
Are you using AbstractBillingActivity or BillingController directly?

What do you mean by "it did the purchase"?

BillingController already includes a call to the Android Market UI.

**Comment by tomer-ben-david** [comment]
Hi

I extended AbstractBillingActivity and called requestPurchase("myitemid"); from within my activity.
was it supposed to show a dialog box?
(maybe i did something wrong...) thanks

**Comment by robotmedia** [comment]
Yes, the Android Market should show up eventually.

Please check the logcat and that in-app billing is supported on your device. If you post the relevant logs here we might be able to help you further.

**Comment by tomer-ben-david** [comment]
everything is ok.
my prob i didn't notice the screen.
