### ISSUE TITLE
Subclass PreferenceActivity

### ISSUE THREAD

**Issue by and7ey** [robotmedia/AndroidBillingLibrary#20]
There should be some other way to use AndroidBillingLibrary instead of 

``` java
extends AbstractBillingActivity
```

used currently. I had to modify `AbstractBillingActivity` to use this library with `PreferenceActivity`.

**Comment by hpique** [comment]
In the meantime, why don't you use BillingController directly? AbstractBillingActivity is just a few lines of code.

**Comment by hpique** [comment]
For clarity's sake, we have decided against providing a `PreferenceActivity` subclass. If needed it can be easily implemented using `AbstractBillingActivity` as a basis.
