### ISSUE TITLE
BillingController.isPurchased always returns false

### ISSUE THREAD

**Issue by and7ey** [robotmedia/AndroidBillingLibrary#21]
I have two activities - `MainActivity extends ListActivity` and `Preferences extends AbstractBillingActivity`.

If `BillingController.isPurchased` is called at `MainActivity`, then `false` is always returned. But if it is called at `Preferences`, then it returns correct value (`true`). 
Why it happens so?

**Comment by hpique** [comment]
Nope. Debugging BillingController.isPurchased step-by-step might help to give you an idea of what's different. 

Please let us know when you find what's amiss.

**Comment by and7ey** [comment]
I see that it fails at `getSalt` with error

> Can't (un)obfuscate purchases without salt

Looks like I need to call `BillingController.setConfiguration` before using `BillingController.isPurchased`. But I am not sure how to call that.

`IConfiguration` methods are implemented at `Preferences` already.

**Comment by hpique** [comment]
Please check DungeonsRedux.

**Comment by and7ey** [comment]
Yes, I am checking that. But this example implements BillingController.IConfiguration, that's why it is possible to call BillingController.setConfiguration(this). I don't want to implement the same at my MainActivity, since I already do that at Preferences activity.

**Comment by hpique** [comment]
You can do it somewhere else then. Maybe in an Application subclass.

**Comment by and7ey** [comment]
hpique, sorry for asking such simple questions (which are not related to AndroidBillingLibrary directly).
I've implemented them

``` java
public class MyApp extends Application implements BillingController.IConfiguration {
```

How should I use now BillingController.setConfiguration? What should be passed as parameter? 

Thank you.

**Comment by and7ey** [comment]
Aaah, ok, I should call that at MyApp class.
