### ISSUE TITLE
Method to get transaction of the last purchase of an item

### ISSUE THREAD

**Issue by lujop** [robotmedia/AndroidBillingLibrary#24]
It will be nice to have a method to obtain the last transaction of a purchased item.
That can be util to look for purchaseTime and implement time limited purchases.

Proposed patch:
diff --git a/AndroidBillingLibrary/src/net/robotmedia/billing/BillingController.java b/AndroidBillingLibrary/src/net/robotmedia/billing/BillingController.java
index e3c315f..a9da843 100644
--- a/AndroidBillingLibrary/src/net/robotmedia/billing/BillingController.java
+++ b/AndroidBillingLibrary/src/net/robotmedia/billing/BillingController.java
@@ -191,6 +191,26 @@ public class BillingController {
        }
        return count;
    }
-   
-   /**
-    \* Returns transaction information of the last purchase of an item.<br/>
-    \* Please take note that this method doesn't take in account cancelations or refunds. 
-    \* @param context
-    \* @param itemId 
-    \* @return Last purchase ransaction of item or null if not found
-    */
-   public static Transaction getLastPurchase(Context context,String itemId) {
-       Transaction lastTransaction=null;
-       List<Transaction> transactions=getTransactions(context,itemId);
-       for(Transaction transaction:transactions) {
-           if(lastTransaction==null || transaction.purchaseTime>lastTransaction.purchaseTime) {
-               if(transaction.purchaseState==PurchaseState.PURCHASED) {
-                   lastTransaction=transaction;
-               }  
-           }  
-       }
-       return lastTransaction;
-   }   
  
  /**
  ##  \* Requests purchase information for the specified notification. Immediately
  
  1.7.6.msysgit.0

**Comment by hpique** [comment]
Given that this method can be easily implemented from `getTransactions(context, itemId)`, I think it would be best not to include it in `BillingController`. 

`BillingController` should provide mostly primitives to work with in-app billing at a higher-level. If a method can be implemented using other methods from `BillingController`, it's a strong sign that it shouldn't be in `BillingController`.

That said, we might include a time-limited purchases or subscription helper built on top of `BillingController` when the library is mature enough.

**Comment by lujop** [comment]
Good design point. I will ad in a custom helper then.
