### ISSUE TITLE
Primary Key of BillingDB is wrong

### ISSUE THREAD

**Issue by lujop** [robotmedia/AndroidBillingLibrary#27]
That's an important one as it can leave the database in a inconsistent logical state.

With current PK if you buy, cancel and buy another time the purchaseCount is 0 because as the pk is only the order IF the first purchase is lot (overriden with the cancel of the order).

The PK should be at least order_id and column_state. I think that product_id should be and I'm unsure about purchasing_time.
I also think that Transaction equals should replicate the same "bussines key" we choose in database.

Suggested patch:

```
From 100eabab7e107b5915f49fd841a09d1fa8bc4b62 Mon Sep 17 00:00:00 2001
From: lujop <joanpujol@gmail.com>
Date: Sat, 23 Jul 2011 16:39:11 +0200
Subject: [PATCH 3/3] Change the PK of table to don't override purchases with
 cancelations or refunds

---
 .../net/robotmedia/billing/model/BillingDB.java    |    6 ++++--
 1 files changed, 4 insertions(+), 2 deletions(-)

diff --git a/AndroidBillingLibrary/src/net/robotmedia/billing/model/BillingDB.java b/AndroidBillingLibrary/src/net/robotmedia/billing/model/BillingDB.java
index a56a80b..71779de 100644
--- a/AndroidBillingLibrary/src/net/robotmedia/billing/model/BillingDB.java
+++ b/AndroidBillingLibrary/src/net/robotmedia/billing/model/BillingDB.java
@@ -97,11 +97,13 @@ public class BillingDB {

         private void createTransactionsTable(SQLiteDatabase db) {
             db.execSQL("CREATE TABLE " + TABLE_TRANSACTIONS + "(" +
-                   COLUMN__ID + " TEXT PRIMARY KEY, " +
+                   COLUMN__ID + " TEXT, " +
                    COLUMN_PRODUCT_ID + " INTEGER, " +
                    COLUMN_STATE + " TEXT, " +
                    COLUMN_PURCHASE_TIME + " TEXT, " +
-                   COLUMN_DEVELOPER_PAYLOAD + " INTEGER)");
+                   COLUMN_DEVELOPER_PAYLOAD + " INTEGER, " +
+                   "PRIMARY KEY("+COLUMN__ID+", "+COLUMN_PRODUCT_ID+", "+COLUMN_STATE+") "+
+                   ")");
         }

        @Override
-- 
1.7.6.msysgit.0
```

**Comment by hpique** [comment]
The Dungeons example by Google also uses the order id as the primary key. Are you sure this is a bug?

**Comment by lujop** [comment]
Ups, I don't looked at dungeons example.
Now that you say I think that we possibly can .leave the PK but then countPurchasesNet has no sense to me as countPurchases has always the most recent version as I suppose that billing sent notificatios in order.

What I can confirm is that countPruchasesNet with current PK gives bad results for a buy,cancel,buy because it returns 0.
I haven't acces to the Dungeons example now, but it has the countNet version?

**Comment by hpique** [comment]
It might be that the `Net` methods are not necessary. I will check the documentation to confirm if cancellations and refunds always use the order id of a previous purchase.
