### ISSUE TITLE
How to properly hide public key?

### ISSUE THREAD

**Issue by and7ey** [robotmedia/AndroidBillingLibrary#29]
Documentation says:

> To keep your public key safe from malicious users and hackers, do not embed your public key as an entire literal string. Instead, construct the string at runtime from pieces or use bit manipulation (for example, XOR with some other string) to hide the actual key. The key itself is not secret information, but you do not want to make it easy for a hacker or malicious user to replace the public key with another key.

How to do the same with AndroidBillingLibrary?

**Comment by hpique** [comment]
You can simply follow Google's recommendation in your `BillingController.IConfiguration.getPublicKey` implementation.
