### ISSUE TITLE
Cancelled order still returned with state PurchaseState.PURCHASED

### ISSUE THREAD

**Issue by martinst** [robotmedia/AndroidBillingLibrary#31]
I created an example project closely modelled on DungeonsRedux. It works just fine and I was able to purchase an item. However after I then cancelled that order in my Google merchant account BillingController.getTransactions() still returns a transaction with the state PurchaseState.PURCHASED

Shouldn't cancelled orders be handled automatically by the library, or do I have to manually handle cancellations in some way?

**Comment by robotmedia** [comment]
Cancelled orders should be handled automatically by the library.

Eventually, you should receive PurchaseState.CANCELLED transaction from the Market and the library will add it to the transaction database automatically.

If you never receive this transaction, try restoreTransactions and see what happens.

**Comment by martinst** [comment]
I guess this could be a problem on Google's end. There seems to be known bugs that makes some messages disappear http://code.google.com/p/marketbilling/issues/detail?id=14

In production it would be impossible to tell whether cancelled orders have been updated on customer phones or not. Running restoreTransactions to often can also cause quota problems. Any ideas on how to know when to run restoreTransactions?

**Comment by robotmedia** [comment]
Nope. As far as I know the quota limits are not documented, so anything we tell you would be a wild guess.
