### ISSUE TITLE
Remove transaction data if associated account removed from device

### ISSUE THREAD

**Issue by uintaam** [robotmedia/AndroidBillingLibrary#36]
If possible it would great to have an option to remove transaction data and do a restore in the case that the user's market account has been removed or changed on the device.

**Comment by robotmedia** [comment]
Interesting. We didn't think of this scenario.

I wonder if there's any way to find out which Android Market account corresponds to a particular transaction. As far as I know this information is not provided by the Android Market.

Any ideas?

In any case, if you remove all transactions you can do this simply by deleting the database.

**Comment by uintaam** [comment]
Off the top of my head, if there is no information provided by the market, we could store a list of attached google.com accounts using

Account[] accounts = accountManager.getAccountsByType("com.google");

Store that list in the database and on start, if any of the accounts in that list were deleted then run a restore in the background and compare the restored transactions against the transactions in the database.  If no order id's match then wipe the database and add the new restored transactions to the list.

**Comment by robotmedia** [comment]
The thing is that you can change the Android Market account to any of your registered accounts, and that wouldn't work with this method. 

Do you know if there's a way to know which account is associated to the Android Market?

**Comment by uintaam** [comment]
It might be possible using getAccountsByTypeAndFeatures but I'm unable to find a list of features that can be requested.

**Comment by ludocrazy** [comment]
i might be mistaken, but i thought to have understood from the offficial google documentation on the market and its behaviour, that only the phones PRIMARY account is used / can be used for purchasing. which means, to remove / switch that account a full device WIPE is needed, which will also wipe the transactions db the android billing library uses as storage.

if i am correct, then this issue can be closed!
