### ISSUE TITLE
Support custom Verification/Security

### ISSUE THREAD

**Issue by mimminito** [robotmedia/AndroidBillingLibrary#4]
The only issue I can see so far is that there is no easy way to allow custom verification/security classes and methods.

For example, we do all of our verification on a server, so we need to use a custom verify method.

If there is a way this can be done, please let me know.

Edit: To help clarify why I am asking for this, if you check the Android Documentation they request that you do verification on a server due to security risks.

Adam

**Comment by robotmedia** [comment]
We were thinking of adding an interface for custom verification. What would be the ideal verification interface for you?

**Comment by mimminito** [comment]
Ideally to be able to override just the verify() method would be great. Provide this as an interface like you have the other methods that are exposed in the AbstractBillingActivity, and your onto a winner :) Most people will not need to do much else than that

**Comment by hpique** [comment]
You can now use `BillingController.setSignatureValidator` to provide your own signature validation.
