### ISSUE TITLE
Item Unavailable for my own in-app products

### ISSUE THREAD

**Issue by estechco** [robotmedia/AndroidBillingLibrary#40]
Hi,

I have followed through with your DungeonRedux example and set my own app in exactly the same way, however, whenever I go to try and purchase a "real" in-app product, I simply get "Item Unavailable - The item that you requested is not available for purchase".

The android.test.purchased situation seems to work fine, just not my own products.

I had wondered whether my app had to be published (despite the Google documentation suggesting otherwise), but having temporarily published my own test copy of DungeonRedux, I can now see that doesn't help either. For the record, neither "sword_001" & "potion_001" work either. Both return the same message as my own.

Any thoughts gratefully received

Regards

DC

**Comment by estechco** [comment]
A slight addendum to previous comment. Having noticed that I had lost my in-app entry, having recently updated my app, I re-added it once again (and in the process also managed to somehow upgrade Android Market on my device). 

Now the interface is slightly different and I do briefly see a backdrop showing the description that I have assigned to my in-app product, but after a split second of doing so now get "Error - The item that you were attempting to purchase could not be found"

**Comment by estechco** [comment]
...and there's more...

Possibly another goof up on my part. Having now "Published" the in-app product, which I hadn't realised you needed to do in addition to publishing the main app itself, the Market now shows me the in-app product in full and my defined credit card (although not the "fake" test one I was half expecting), but now I get "Error - Your order could not be processed. Please try again".

Possibly another delay, or perhaps I should check my credit card's are all up to date!

**Comment by estechco** [comment]
Now it simply returns me "You already have a pending order for this item". 

Can anyone who has successfully got this all to work offer any constructive advise?

**Comment by dhendo** [comment]
To get the fake credit card option, I believe you need to use the item id "android.test.purchased"
- see http://developer.android.com/guide/market/billing/billing_testing.html

It appears you can't buy an item from yourself. You need to atttempt the purchase from another google account, that is listed as a test account in your market settings. See the "Testing In-app Purchases Using Your Own Product IDs" section in the above document.

This user will be able to purchase items that are published, from an app that is not published on the market.

**Comment by estechco** [comment]
Thankfully, having tested it on a pal's phone it does indeed seem to work. Just a little unnerving in the first instance.

Thanks for your help
