### ISSUE TITLE
Basic example needed

### ISSUE THREAD

**Issue by suomi35** [robotmedia/AndroidBillingLibrary#44]
I see a nice sample app for the BillingController method (DungeonsRedux), but no sample app for the AbstractBillingLibrary method. Does such an example exist?

I have subclassed the AbstractBillingActivity in my own activity, but am getting NPE when calling checkBillingSupported(), for example.

It would be really valuable to see a very basic class showing the subclassing and subsequent calls made, etc.

Thanks,
-Jason

**Comment by robotmedia** [comment]
AbstractBillingActivity is just a convenience class around BillingController. Even if we eventually add an example app using it, it is highly recommended to get acquainted with BillingController before using this library.

Please post the NPE stack trace in a separate issue so we can give it a look.

Thanks.

**Comment by suomi35** [comment]
Thanks very much...I think I have solved it now.
