### ISSUE TITLE
The buy button is greyed

### ISSUE THREAD

**Issue by maximeloridan** [robotmedia/AndroidBillingLibrary#50]
I open "Dungeons Redux" and, as expected, the "buy" button can be clicked.
But, if i click the back button on my phone, and then reopen "Dungeons Redux", then the "buy" button is greyed.

It seems that "onBillingChecked" on "Dungeons.java" is not called the second time.
Am I missing something?

**Comment by serso** [comment]
In Dungeons Redux any item can be bought only one time - so if you've already bought it the program checks the state of transaction and if it is verified (I mean purchased) the item is become disabled (greyed).

**Comment by powder366** [comment]
This is not the case for me, why is this not called:

```
public void onBillingChecked(boolean supported) {
    if (supported) {
        restoreTransactions();
        mBuyButton.setEnabled(true);
    } else {
        showDialog(DIALOG_BILLING_NOT_SUPPORTED_ID);
    }
}
```
