### ISSUE TITLE
Is restoreTransaction() should be called more than once ?

### ISSUE THREAD

**Issue by grunk** [robotmedia/AndroidBillingLibrary#54]
I'm trying your library with the Dungeons Redux sample. At some point we can find something like that : 

``` public void restoreTransactions() {
    if(!mBillingObserver.isTransactionsRestored())
        BillingController.restoreTransactions(this);
        ....

``````

 ```BillingController.restoreTransactions(this)``` is called each time the app is launching and not only the first time. Is that because there is nothing to restore or should i manually write some shared preference ?
``````

**Comment by hpique** [comment]
In the Dungeons Redux example AbstractBillingObserver is used to handle this. Once transactions are restored for the first time a preference is written to avoid doing it again.
