### ISSUE TITLE
Market crashes doing any action in Dungeons example

### ISSUE THREAD

**Issue by iranedo** [robotmedia/AndroidBillingLibrary#56]
I joined the code that is available in the github with no modifications int the code and when I' trying to do any action (purchase, cancel, refund, etc...) the market opens and inmediatly crashes why is that happening?
Thank you for your time

**Comment by iranedo** [comment]
It was because the device had the Titanium backup

**Comment by hpique** [comment]
Closing and moving the discussion to #70.
