### ISSUE TITLE
isPurchasedNet and countPurchasesNet missing

### ISSUE THREAD

**Issue by pfjborg** [robotmedia/AndroidBillingLibrary#65]
Have downloaded current release of ABL:

commit 34450d05242e37983e2668ca08bcfba2cba1b684
Merge: 0153cf5 bbde40f

BillingController.java is missing the two functions isPurchasedNet() and countPurchasesNet() committed to close issue #3 - were these ever available in a release version of the library?

**Comment by hpique** [comment]
They were removed in commit d6913d7289b0880457a55d9d8ac238a847181a6d as they were redundant.

**Comment by pfjborg** [comment]
In wihch case the question becomes what should I be using in their place to determine if an item is purchased but not subsequently cancelled or refunded?

**Comment by hpique** [comment]
IIRC, if a managed item gets cancelled or refunded the transaction gets updated with the new state. isPurchased should return false.

**Comment by pfjborg** [comment]
Yup, looks like that's right - have tested with a published managed item on an unpublished app, purchased, refunded, isPurchased returns false.

Javadoc for the function is misleading though, hence the original question, states: "Note that if the item was later canceled or refunded this will still return true."

**Comment by hpique** [comment]
Thanks for catching that. Added as bug:

https://github.com/robotmedia/AndroidBillingLibrary/issues/68
