### ISSUE TITLE
onTransactionsRestored never called

### ISSUE THREAD

**Issue by pfjborg** [robotmedia/AndroidBillingLibrary#67]
BillingController.onTransactionsRestored is never called from within the library.

**Comment by hpique** [comment]
It's called from this line:

https://github.com/robotmedia/AndroidBillingLibrary/blob/master/AndroidBillingLibrary/src/net/robotmedia/billing/BillingRequest.java#L172

Or do you mean that line is never reached?

**Comment by pfjborg** [comment]
Insterted a log line at 173 to test, never reached, however....

....it seems this is to do signed/unsigned; when testing with a signed app and non-developer account this works, when testing with unsigned app and developer account (with android.test.\* test products) this line is never reached. I was aware that restoreTransactions would do nothing in unsigned/test app, didn't realise it would affect onTransactionsRestored.

P.S. thanks for all the work, and for all your help...!

**Comment by hpique** [comment]
You're welcome @pfjborg!

**Comment by fraggle222** [comment]
Recommend that this feature(?) get better documented, to save us all the Google search for "onTransactionsRestored never called", thus ending up here. But great Library. Thank you.
