### ISSUE TITLE
Transaction confirmation

### ISSUE THREAD

**Issue by iranedo** [robotmedia/AndroidBillingLibrary#69]
I have a problem and I need some advice cause everything I've done hasn't solve what I need. I have an item that I can purchase as many times as I want, i've tried this 2 ways but both give me different problems:

The function SearchAndSave() refresh the view even before the payment plattform has been launched 
BillingController.requestPurchase(getBaseContext(), "simple.search" /\* confirm*/ );
if(BillingController.confirmNotifications(getBaseContext(), "simple.search"))
{
          SearchAndSave();
}

The function SearchAndSave() is never called, I assume is because requestPurchase just launch the payment plattform but nothing else so the ispurchased() returns false cause when it's called the purchase hasn't been compleated yet
BillingController.requestPurchase(getBaseContext(), "simple.search" /\* confirm*/ );
if(BillingController.isPurchased(getBaseContext(), "simple.search"))
{
          SearchAndSave();
}

**Comment by hpique** [comment]
requestPurchase is asynchronous. You should do any post-purchase logic in onPurchaseStateChanged.

**Comment by iranedo** [comment]
That worked perfectly! Thanks!
