### ISSUE TITLE
Handling response codes (IN_APP_NOTIFY)

### ISSUE THREAD

**Issue by richardleggett** [robotmedia/AndroidBillingLibrary#7]
How are you handling response codes after a purchase is made. BillingController is logging them in debug mode, but no callback on IBillingObserver is made?

**Comment by robotmedia** [comment]
That's right. Is there any use case to propagate the response codes to the billing observer?

**Comment by richardleggett** [comment]
Actually, I'm not sure if this is because I'm on Honeycomb, but when the user clicks OK or Cancel in the Market dialog, the BillingReceiver never calls notify(), it never receives an IN_APP_NOTIFY intent, only RESPONSE_CODE. So BillingController never continues the message sequence and never requests the GET_PURCHASE_STATE_CHANGED.

This should happen automatically right? Or do we need to do something in the middle here?

**Comment by richardleggett** [comment]
So I have run the code on Gingerbread and it works fine. Honeycomb's Android Market app is not sending the IN_APP_NOTIFY broadcast. Have you guys had a try yet?

**Comment by richardleggett** [comment]
After a reboot (Xoom), I got ALL the PURCHASE_STATE_CHANGEs for all these purchases, all queued up. Here's a bug related to the problem:

http://code.google.com/p/android/issues/detail?id=16042#c8

**Comment by robotmedia** [comment]
Regrettably Google's in-app billing service still has a few critical known bugs.
