### ISSUE TITLE
Support the new in-app subscriptions

### ISSUE THREAD

**Issue by mattiasbe** [robotmedia/AndroidBillingLibrary#72]
Please add support for the new in-app subscriptions launched today.

See:
http://android-developers.blogspot.se/2012/05/in-app-subscriptions-in-google-play.html

And more specifically:
http://developer.android.com/guide/market/billing/billing_subscriptions.html#version

**Comment by tszming** [comment]
+1 for this feature.

**Comment by klemensz** [comment]
+1 for this feature.

**Comment by hpique** [comment]
Just added this today with minimal testing. Feel free to give it a go and send feeback.

**Comment by klemensz** [comment]
Thanks! Will test it...
