### ISSUE TITLE
Support for static response testing

### ISSUE THREAD

**Issue by cherrydev** [robotmedia/AndroidBillingLibrary#73]
I think it would be very useful to have a configuration mode that would allow for 'almost' end-to-end testing of the billing process using the static responses with the specified item IDs, like "android.test.purchased".  This can be done now by just requesting a purchase of that itemId, but there's currently no way to map that to an 'actual' item.  I suggest that this could be done using the developer payload.  Just before the request to the Play service gets made, swap the 'actual' item ID with the static test ID, and stuff the actual item ID into a field in the payload.  When the result comes back, do the opposite.  This will allow the fake purchase to be recorded into the purchase database, etc, etc.

I'm on a deadline, so I'm going to try to hack together a quick implementation of this, but what I right will probably not be appropriate to be included into the app.

**Comment by cherrydev** [comment]
Crap, this approach won't work.  It does not return the developer payload that's sent with a testing ID.  Next approach is to use the returned REQUEST_ID to match the request with the response.

**Comment by hpique** [comment]
The in-app billing service doesn't appear to be designed to support end-to-end testing.

For now, I think it's best to resign ourselves to test with real item ids.
