### ISSUE TITLE
Check for single purchase.

### ISSUE THREAD

**Issue by f2prateek** [robotmedia/AndroidBillingLibrary#74]
I'm trying to check for a single purchase to remove ads. The method returns false if the purchase is not made, and then the activity goes to display ads. IN_APP_REMOVE_ADS is the purchaseID. Unfortunately the code doesn't seem to work with android.test.purchased as the id

private Boolean checkAdPurchase() {
        Log.v(TAG, "checkAdPurchase() ");

```
    List<Transaction> transactions = BillingController.getTransactions(
            this, IN_APP_REMOVE_ADS);
    for (Transaction t : transactions) {
        if (t.purchaseState == PurchaseState.PURCHASED) {
            return true;
        }
    }
    return false;
}
```

**Comment by hpique** [comment]
Use real ids. The android.test.\* item ids are no good for testing the complete purchase process.

**Comment by f2prateek** [comment]
Yeah I realized that later. Sorry I forgot to close issue. Thanks :)
