### ISSUE TITLE
Sample app

### ISSUE THREAD

**Issue by t0mm13b** [robotmedia/AndroidBillingLibrary#75]
Dungeons redux, tapping on buy, yields this in the logcat

`I/ActivityManager(  243): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=t0mm13b.dungeonsRedux/.Dungeons bnds=[83,296][158,406] } from pid 380
I/ActivityManager(  243): Displayed t0mm13b.dungeonsRedux/.Dungeons: +353ms
D/dalvikvm( 8618): GC_CONCURRENT freed 294K, 47% free 3093K/5831K, external 915K/1427K, paused 2ms+3ms
W/InputManagerService(  243): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2b4f50e8
W/BillingService( 8618): Remote billing service crashed`

Why did billingservice crash? The strange thing was I fired up the original Dungeons and that works... so something in the BillingService.java's routine `runRequest` seems to be broken! Suggestions?

**Comment by hpique** [comment]
Can you reproduce the problem more than once?

If so, can you provide more info about the device?
