### ISSUE TITLE
item not found?

### ISSUE THREAD

**Issue by ytzhakov** [robotmedia/AndroidBillingLibrary#76]
I've tried using this library but I get "item not found" every time i try to purchase an item.
I've added sword_001 to the apps items list and I've set a test account (not my developer account)
I've also set my public key where the documentation said

any ideas?

**Comment by hpique** [comment]
Hey @ytzhakov. 

Follow http://developer.android.com/guide/google/play/billing/billing_testing.html by the letter. Check the logcat for clues.
