### ISSUE TITLE
Usage clarifications to be added

### ISSUE THREAD

**Issue by and7ey** [robotmedia/AndroidBillingLibrary#8]
It is not quite clear where to input public key and in which format. Shoud I return that as result in getPublicKey()?
Also not quite clear how 'salt' related functions should be used (and what they are for).

Not quite clear what is automated with regards to the database - what is written automatically there?

**Comment by robotmedia** [comment]
If you're using `AbstractBillingAcitvity` then you only need to implement the methods inherited from `BillingController.IConfiguration`. The Javadoc indicates the format of the key (base64) and what's the salt for (to obfuscate transactions in the database).

The database automatically stores all transactions (purchases, cancellations and refunds). No more, no less.

**Comment by and7ey** [comment]
Thanks, robotmedia.

I am doing the following:

```
private static final String ANDROID_MARKET_ITEM = "android.test.purchased";
requestPurchase(ANDROID_MARKET_ITEM);
```

But `onPurchaseExecuted` is not called. Purchase Dialog is just closed.

What is wrong here?
Also, if after that I check the database:

```
BillingDB bDB = new BillingDB(getApplicationContext());
Cursor purchases = bDB.queryPurchases();
Log.i(TAG, "Count: " + purchases.getCount());
```

I see that no records are added to the database.

**Comment by robotmedia** [comment]
Please open a separate issue for this. Thanks.

**Comment by and7ey** [comment]
New issue has been created.
