### ISSUE TITLE
Purchased Failed Notifications

### ISSUE THREAD

**Issue by kenyu73** [robotmedia/AndroidBillingLibrary#82]
Problem: If an in-app purchase fails or an order is cancelled/refunded, there is a recurring "Purchased Failed" error in the notification bar. Even if the user fixed the credit card and purchases it successfully, this notification still occurs even though the billing code does get the final PURCHASED id. This occurs over and over again it appears. The only fix is to remove the app for good.

This appears reproducible. 
  1) Purchase in-app item
  2) Cancel item
  3) Reboot device (being out of data service for an extended time can do this too)
  4) Note Purchased Failed notification shortly after reboot.

I know that the full purchase history for an app is piped through the code. Is it the Market that generates this notification or the BillingLibrary? Can it be fixed or is this a Play Store issue? 

Similar to #49

**Comment by hpique** [comment]
I believe the problem here is that you need to manually confirm the cancel/refund notification. See also #28.

**Comment by kenyu73** [comment]
Looks like this is the fix!

BillingController.confirmNotifications(this, itemId);   

```
@Override
public void onPurchaseStateChanged(String itemId, PurchaseState state) {
    Log.d(TAG, "AbstractBillingLibrary::onPurchaseStateChanged(): " + itemId + ":" + state);

    SharedPreferences prefs = getPreferences(Context.MODE_PRIVATE);
    SharedPreferences.Editor edit = prefs.edit();

    if (state == PurchaseState.PURCHASED) {
        edit.putBoolean(itemId, true);
        makePremiumView();
    } else {
        BillingController.confirmNotifications(this, itemId);
        edit.putBoolean(itemId, false);
    }

    edit.commit();
}
```

**Comment by hpique** [comment]
Yes, that should work. We will add auto-confirmations for cancellations and refunds in a future update.
