### ISSUE TITLE
Problem with subscription

### ISSUE THREAD

**Issue by oibaf79** [robotmedia/AndroidBillingLibrary#83]
i'm using the DungeonsRedux and trying the subscription service.
I can buy a subscription through the app but after bought the subscription i return in the app and i can't see the bought subscription, the code:
for (Transaction t : transactions) {
    if (t.purchaseState == PurchaseState.PURCHASED) {
        ownedItems.add(t.productId);
    }
}
ownedItems is empty and the method onPurchaseStateChanged is never called.

How i can fix this problem?

Thank you very much.

**Comment by hpique** [comment]
Did you upload the APK to your Google Play account and created the in-app items?

**Comment by oibaf79** [comment]
Yes, and i can buy the subscriptions, but when return in the app ownedItems is empty and the method onPurchaseStateChanged is never called.

**Comment by hpique** [comment]
Do in-app products (not subscriptions) work?

Logcat?

**Comment by oibaf79** [comment]
neither the in-app product works, i can buy but after that ownedItems is always empty.

I can't use the Logcat because i can't test the in-app on the emulator but only on a real smartphone :(

**Comment by hpique** [comment]
You can get the logcat from a device too.
