### ISSUE TITLE
Add SherlockFragmentActivity and SherlockActivity-compatible versions of the default classes

### ISSUE THREAD

**Issue by davefp** [robotmedia/AndroidBillingLibrary#85]
Having default Activity and Fragment classes to subclass is great, but if you're using ActionBarSherlock you're forced to subclass either SherloclActivity or SherlockFragmentActivity so you can't use the Billing ones.

It would be great to expose Sherlock-compatible versions of the Activity/Fragment classes to make it easier to work with ABS and ABL together :)

**Comment by hpique** [comment]
Why make ABL depend on ABS if you can just copy and paste a few lines of code? AbstractBilling[Activity|Fragment] are just convenience classes.

**Comment by christopherperry** [comment]
Yep, that's what I did. I'm also using Roboguice.

**Comment by hpique** [comment]
@christopherperry +1 for Roboguice. ;)
