### ISSUE TITLE
Verifying application with test items

### ISSUE THREAD

**Issue by and7ey** [robotmedia/AndroidBillingLibrary#9]
I am doing the following:

```
private static final String ANDROID_MARKET_ITEM = "android.test.purchased";
requestPurchase(ANDROID_MARKET_ITEM);
```

But `onPurchaseExecuted` is not called. Purchase Dialog is just closed.

What is wrong here?
Also, if after that I check the database:

```
BillingDB bDB = new BillingDB(getApplicationContext());
Cursor purchases = bDB.queryPurchases();
Log.i(TAG, "Count: " + purchases.getCount());
```

I see that no records are added to the database.

**Comment by and7ey** [comment]
Btw, I also have the following code now:

```
@Override
public byte[] getObfuscationSalt() {
    return null;
}

@Override
public String getPublicKey() {
    return "here is my key copied from market publish page";
}
```

**Comment by and7ey** [comment]
Btw, I also see the following record at LogCat:

> 07-08 13:54:03.636: DEBUG/BillingController(29306): Request 5419304117851015224 received response RESULT_OK

But 

```
PurchaseManager.isPurchased(getApplicationContext(), ANDROID_MARKET_ITEM)
```

returns false.

**Comment by and7ey** [comment]
By debugging the code I've observed the following:
1. `onReceive#BillingReceiver` calls `responseCode(context, intent)`, not `purchaseStateChanged(context, intent)`. Is that correct (http://developer.android.com/guide/market/billing/billing_overview.html#billing-action-notify)? Looks like it happens so, since I've already purchased this item before while testing another application.
   Probably, it will not work correctly with unmanaged items (http://developer.android.com/guide/market/billing/billing_admin.html#billing_purchase_type) also.
2. `onPurchaseStateChanged#BillingController` receives empty `signedData`. Probably it happens so because data received for test items is not signed?

**Comment by robotmedia** [comment]
Are you using `BillingController.setDebug(true)`?

**Comment by and7ey** [comment]
Yes. See no other errors in the LogCat.

**Comment by and7ey** [comment]
If I use restoreTransactions, then onPurchaseStateChanged is never called, in result purchases are not saved in database.

**Comment by and7ey** [comment]
robotmedia, will you be able to help me with this?

**Comment by robotmedia** [comment]
_Re: question 1_

After a purchase request `BillingReceiver` should receive both a `RESPONSE_CODE` and then an `IN_APP_NOTIFY` action. `BillingReceiver` will respectively call `BillingController.onResponseCode` and `BillingController.onNotify`. 

The `RESPONSE_CODE` is simply to indicate if the request was successfully received by the Android Market server. From the Android documentation:

> This response contains an Android Market server response code, and is sent after you make an in-app billing request. A server response code can indicate that a billing request was successfully sent to Android Market or it can indicate that some error occurred during a billing request. This response is not used to report any purchase state changes (such as refund or purchase information).

`PURCHASE_STATE_CHANGED` comes after the `IN_APP_NOTIFY`. This is the typical flow:

![Billing request flow](http://developer.android.com/images/billing_request_purchase.png)

The behavior here is the same if the item is managed or unmanaged.

_Re: question 2_

It seems from this that you're eventually received `PURCHASE_STATE_CHANGED`. If `signedData` is `null`, well, there's not much that our library can do. It can be `null` for many reasons. This might help: http://developer.android.com/guide/market/billing/billing_testing.html

_Re: restoreTransactions question_

Most likely the same thing that was giving you a null signedData before is at play here.

Hope this helps. Please let us know what was the issue when you solve it.

**Comment by and7ey** [comment]
Thanks for your reply.

_Re: question 1_
I've tested that with `requestPurchase`.

`IN_APP_NOTIFY` is not received.

_Re: question 2_
I've tested that with `restoreTransactions`. Will try to understand why data received is not signed.

**Comment by and7ey** [comment]
> > IN_APP_NOTIFY is not received.
> 
> Are you sure? Then how are you reaching `BillingController.onPurchaseStateChanged` afterwards? Bear in mind the `BillingReceiver` receives asynchronous messages.

`onPurchaseStateChanged` is reached with `restoreTransactions`, not with `requestPurchase`.

**Comment by and7ey** [comment]
Hmm, looks like the problem is caused by usage of test account on the device, not developer's account (however, test account is added to the list of test accounts).

**Comment by and7ey** [comment]
OK, when I've started to use developer's account on the device, it is started to work better.
Now I see that purchase of _android.test.purchased_ is reflected in the database. But purchase status there is 0. Hence `isPurchased` returns false. 

I've checked possible states

``` java
    public enum PurchaseState {
        // Responses to requestPurchase or restoreTransactions.
        PURCHASED,    // 0: The charge failed on the server.
        CANCELLED,   // 1: User was charged for the order.
        REFUNDED;    // 2: User received a refund for the order.
```

Is everything correct here?

**Comment by and7ey** [comment]
And it is still work incorrectly with `restoreTransactions`. Looks like it can not be used with reserved items - http://stackoverflow.com/questions/6640480/why-restore-transactions-in-app-billing-returns-not-signed-data.

Btw, could you please provide me with example how `public byte[] getObfuscationSalt() {` can look like?

**Comment by robotmedia** [comment]
Can you open separate issues for both the PurchaseState and salt questions? 

If you do we will reply ASAP. Thanks.
