### ISSUE TITLE
Etiquette for using this library

### ISSUE THREAD

**Issue by IntegersOfK** [robotmedia/AndroidBillingLibrary#93]
Hi there!

Love this library... seems to be working really well for my app. I'm sort of a programming newb. Please excuse me if this is the wrong place for this post; please let me know where I should go if this is the case.

I've never actually used an open source library in an app before, so I just wanted to check in with how I should go about a couple of things:
1. My app is also open source, but I threw the GNU type license on it. Am I to use the same license as the project, or will this be fine?
2. How do I reference contributions? Should I simply put a link to the library in my README or something? I just want to make sure I'm not stepping on any toes and ensure that contributions are sourced correctly.
3. Could somebody please link me or explain how to implement the library in a way that makes it easy to update? Currently I've just sort of copied the files into my project, but it's my understanding that there's someway in Eclipse to 'link' a library rather than copying the Java files directly.

Thanks for all this.

**Comment by ludocrazy** [comment]
on point 3 (as far as i remeber how i did it)
-copy the files of the android billing library into your workspace, add the library as a new project to the package explorer (file -> new , etc.)
-in eclipse open the project in the package explorer you want to add the library.
-right mouse on the project to access properties.
-on the left access android properties (where you can set project build target in the upper part)
-in the lower part click ADD and chose the android billing library
HINT: this only works if the library (the project in your workspace) is set as "IsLibrary" (which it is on default)

if i am mistaken or missed a step (wrote this down just how i remembered it) please correct me.

on point 2:
-i am no expert and do not if there is a general rule followed by people, but its working quite well if you just add a readme or credits section in the application where you list everything you use AND for everything the license is under. google android os itself does this similarily. go to your device and access main settings, head for "about tablet" or something similar (depending on android os version), go for "legal information" (android ics) or something similar and there are all licenses for used parts/libraries.

on point 1:
-its quite a difficult task deciding what licenses want. there is a lot of literature out there. please google explanatory texts. you might start with just reading wikipedia articles on that.
-a basic way to go is: if your overall license is more restrictive (in terms of opensource) then thats fine, as long as people can still see that the parts of your library are licensed less restrictive (for example allowing commercial use). if your overall license is less restrictive (e.g. allows for commerical use) then you most likely are not allowed to use the libraries with more restrictiv licenses anyway or you use one of the (possible) loopholes (like bundling precompiled DLLs on windows) and then i would guess you have already precise knowledge about sub licenses and wouldn't ask this question here ;)

if you feel satisfied with my answers please close this issue. generally this is an issue tracker for this library, your questions are very broad and should be addressed to different parts of the internet (tech questions might go to stackoverflow.com, licensing questions personally to the original author of this library, general questions into general forums ;)

**Comment by hpique** [comment]
Hi @IntegersOfK.

This library is licensed under [Apache 2.0](http://www.apache.org/licenses/LICENSE-2.0) so you should be fine. The license text is short, so you might want to give it a read just in case. Question 2 in particular is answered in the Redistribution section of the license.

Happy coding!
