### ISSUE TITLE
"Item unavailable" error

### ISSUE THREAD

**Issue by sjvc** [robotmedia/AndroidBillingLibrary#96]
I'm trying to use this library to implement in app billing to accept donations in my app (my app will sell unmanaged items called "donations"). When I call to requestPurchase(STORE_ITEM_ID); appears the Google Play screen showing my unmanaged item correctly, but after a second a popup is shown and says: "The item you requested is not available for purchase".... This is what I did:

1 - In my app: I created a new Activity that extends AbstractBillingActivity. I've overriden getObfuscationSalt method, it returns a byte array with 20 random digits. I've overriden getPublicKey method, it returns the public key I get in my developer console. I check if billing is supported using onBillingChecked, and finally when the user press the "donate" button I call requestPurchase if billing is supported.

2 - In my developer console: I uploaded a new app signed (but is not published, only uploaded). I created a new unmanaged item, and I activated it. Then I added a new gmail test account. Then I used a real android device to test it, I did a hard reset and l used my gmail test account. I installed my app (the same version I uploaded), and.... thats all

What I'm doing wrong? Can you help me please?

**Comment by sjvc** [comment]
I published the app and now it works ok...

**Comment by jthomaschewski** [comment]
I have the same issue but I think it's not related to this library as this seems to be an error response from the Google servers. According to Google publishing the In-App item and adding the test account should be sufficient but in some cases it just doesn't work as expected.

Does anyone else have this problem with this library or can confirm that it is/is not library related?

**Comment by lakeba** [comment]
I am using a different account then my play console account and debugging
on a real device.
In my case the play store reply as expected and as a real account.
Il giorno 27/ott/2012 16:36, "jbbr" notifications@github.com ha scritto:

**Comment by davidcaste** [comment]
Sometimes Google Play takes some time to correctly register/activate/propagate/whatever-it-does-internally after a in-app purchase is registered, and until it is finally available worldwide. That is something which could drive you crazy to realize if you don't know in advance. I've seen so many threads in Stackoverflow about that problem.

**Comment by hpique** [comment]
As @davidcaste mentioned, Google Play might take a while to make the items "available" (in my experience 2 hours is enough). This is a known issue of Google Play, but I haven't seen it officially documented yet.
